robots:
  limo:
    topics:
      odom: "/odom"
      reached_goal: "/topoplan/reached_goal"
      cmd_teleop: /cmd_vel_teleop
      cmd_model: /cmd_vel_navigate
      closest_node: "/closest_node"
    data_header:
      odom:
        pose_x: pose.pose.position.x
        pose_y: pose.pose.position.y
        time_odom: Time
      cmd_teleop:
        lin_x_teleop: linear.x
        lin_y_teleop: linear.y
        time_teleop: Time
      cmd_model:
        lin_x_model: linear.x
        lin_y_model: linear.y
        time_model: Time
      closest_node:
        closest_node: data
        time_closest_node: Time
      reached_goal:
        goal: data
        time_goal: Time
    process_bag_metrics:
      img_process_func: "process_custom_img"
      odom_process_func: "nav_to_xy_yaw"
      image_topic: "/camera/image_raw" # Needed for closest node plotting


environments:
  sim:
    - clearpath_playpen
  indoor:
    - mist_office_v1
    - hallway
  outdoor:
    - parking_lot
    - forest


# Not implemented yet
# - human
# - object
augmentations:
  - brightness
  - blur
  - fog
  - sunFlare_overlay
  - sunFlare_physic
  - rain
  - rain_heavy
  - rain_drizzle
  - rain_torrential
  - reference # reference trajectory
  - no_augmentation 

paths:
  bags_dir: "/workspace/metrics/bags/"
  dataframes_dir: "/workspace/metrics/dataframes/"
