robots:
  bunker:
    topics:
      odom: "/lvi_sam/lidar/mapping/odometry"
      reached_goal: "/topoplan/reached_goal"
      cmd_model: /cmd_vel
      closest_node: "/closest_node"
    data_header:
      odom:
        pose_x: pose.pose.position.x
        pose_y: pose.pose.position.y
        Time: Time
      cmd_model:
        lin_x_model: linear.x
        lin_y_model: linear.y
        Time: Time
      closest_node:
        closest_node: data
        Time: Time
      reached_goal:
        goal: data
        Time: Time
    process_bag_metrics:
      img_process_func: "process_custom_img"
      odom_process_func: "nav_to_xy_yaw"
      image_topic: "/usb_cam/image_raw" # Needed for closest node plotting
  # limo:
  #   topics:
  #     odom: "/odom"
  #     reached_goal: "/topoplan/reached_goal"
  #     cmd_teleop: /cmd_vel_teleop
  #     cmd_model: /cmd_vel #/cmd_vel_navigate
  #     closest_node: "/closest_node"
  #   data_header:
  #     odom:
  #       pose_x: pose.pose.position.x
  #       pose_y: pose.pose.position.y
  #       Time: Time
  #     cmd_teleop:
  #       lin_x_teleop: linear.x
  #       lin_y_teleop: linear.y
  #       Time: Time
  #     cmd_model:
  #       lin_x_model: linear.x
  #       lin_y_model: linear.y
  #       Time: Time
  #     closest_node:
  #       closest_node: data
  #       Time: Time
  #     reached_goal:
  #       goal: data
  #       Time: Time
  #   process_bag_metrics:
  #     img_process_func: "process_custom_img"
  #     odom_process_func: "nav_to_xy_yaw"
  #     image_topic: "/camera/image_raw" # Needed for closest node plotting

# robot_names: ['limo']
robot_names: ['bunker']

environments:
  sim:
    - clearpath_playpen
  indoor:
    - mist_corridor
    - mist_office_17nov
    - hallway
  outdoor:
    - parking_lot
    - forest


# Not implemented yet
# - human
# - object
augmentations:
  - brightness
  - blur
  - fog
  - sunFlare_overlay
  - sunFlare_physic
  - rain
  - rain_heavy
  - rain_drizzle
  - rain_torrential
  - reference # reference trajectory
  - no_augmentation 


radius:
  default: 2
  values:
    - 10


paths:
  bags_dir: "/workspace/metrics/bags/"
  dataframes_dir: "/workspace/metrics/dataframes/"
