robots:
  limo:
    topics:
      odom: "/odom"
      reached_goal: "/topoplan/reached_goal"
      cmd_teleop: /cmd_vel_teleop
      cmd_model: /cmd_vel_navigate
      closest_node: "/closest_node"
    data_header:
      odom:
        pose_x: pose.pose.position.x
        pose_y: pose.pose.position.y
        Time: Time
      cmd_model:
        lin_x_model: linear.x
        lin_y_model: linear.y
        Time: Time
      closest_node:
        closest_node: data
        Time: Time
      reached_goal:
        goal: data
        Time: Time
    process_bag_metrics:  # Needed for closest node plotting
      img_process_func: "process_custom_img"
      odom_process_func: "nav_to_xy_yaw"
      image_topic: "/camera/image_raw"



robot_names: ['limo']

environments:
  sim:
    - sim_test



setup_configs: ['config1']

paths:
  bags_dir: "/workspace/metrics/parameters_analysis/"
  dataframes_dir: "/workspace/metrics/parameters_analysis/"
