name: Mirror to Public Repo vnm-zeroshot-eval
# see for troubleshooting: https://github.com/orgs/community/discussions/60392
on:
  push:
    branches: # Only put the branches you want to mirror
      - ros2/nomad
      - ros2/navibridger
      - bunker/crossformer

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # full history, not just latest commit
          submodules: false     # submodules not needed for mirroring

      - name: Push branch to public mirror vnm-zeroshot-eval
        env:
          TOKEN: ${{ secrets.PUBLIC_VNM_EVAL_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://MaevaGuerrier:${TOKEN}@github.com" > ~/.git-credentials
          git remote add public https://github.com/MaevaGuerrier/vnm-zeroshot-eval.git
          git push public ${{ github.ref_name }}